/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#4648d4',
        secondary: '#6b38d4',
        'primary-container': '#6063ee',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-container': '#8455ef',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#cbdbf5',
          bright: '#f8f9ff',
          container: '#e5eeff',
          'container-low': '#eff4ff',
          'container-high': '#dce9ff',
          'container-highest': '#d3e4fe',
          'container-lowest': '#ffffff',
          variant: '#d3e4fe',
          tint: '#494bd6',
        },
        'on-surface': '#0b1c30',
        'on-surface-variant': '#464554',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#c0c1ff',
        tertiary: '#595c5e',
        'tertiary-container': '#727577',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fbfdff',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        // Dark mode surface overrides applied via CSS variables
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      animation: {
        'blob': 'blob 20s infinite alternate',
        'ping-slow': 'ping 2s cubic-bezier(0,0,0.2,1) infinite',
        'float': 'float 3s ease-in-out infinite',
        'pulse-dot': 'pulseDot 2s infinite',
        'slide-up': 'slideUp 0.4s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
      },
      keyframes: {
        blob: {
          from: { transform: 'translate(-10%, -10%)' },
          to: { transform: 'translate(20%, 30%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseDot: {
          '0%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(70,72,212,0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 10px rgba(70,72,212,0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(70,72,212,0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'glass': '0 4px 20px rgba(99, 102, 241, 0.06)',
        'glass-lg': '0 8px 40px rgba(99, 102, 241, 0.12)',
        'primary': '0 4px 24px rgba(70, 72, 212, 0.25)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
